In [1]:
import numpy as np

# === Boolean Operations ===
print("=== Boolean Operations ===")

# 1. Filtering arrays
array = np.array([1, 2, 3, 4, 5, 6])
filtered_array = array[array > 3]  # Extract elements greater than 3
print("Filtered Array (elements > 3):", filtered_array)

# 2. Logical operations
logical_and_result = np.logical_and(array > 2, array < 5)  # Between 2 and 5
logical_or_result = np.logical_or(array < 2, array > 5)    # Less than 2 or greater than 5
print("Logical AND (2 < elements < 5):", logical_and_result)
print("Logical OR (elements < 2 or > 5):", logical_or_result)

# === Vectorization ===
print("\n=== Vectorization ===")

# Perform element-wise operations directly on arrays
vectorized_result = array * 2 + 5  # Multiply each element by 2, then add 5
print("Vectorized Result (array * 2 + 5):", vectorized_result)

# Avoiding loops with vectorization
large_array = np.arange(1, 1_000_001)  # Array with 1 million elements
sum_result = np.sum(large_array)  # Vectorized summation
print("Sum of 1 to 1,000,000 (Vectorized):", sum_result)

# === Broadcasting and Strides ===
print("\n=== Broadcasting and Strides ===")

# Broadcasting example: Adding a scalar to a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
broadcasted_addition = matrix + 10
print("Broadcasted Addition:\n", broadcasted_addition)

# Broadcasting example: Adding a 1D array to a 2D array
row_vector = np.array([10, 20, 30])
broadcasted_with_vector = matrix + row_vector
print("Broadcasting with Vector:\n", broadcasted_with_vector)

# Strides example: View of every second column
strided_view = matrix[:, ::2]
print("Strided View (Every 2nd Column):\n", strided_view)

# === Structured Arrays ===
print("\n=== Structured Arrays ===")

# Creating a structured array with custom dtypes
structured_array = np.array([(1, 'Alice', 85.5), 
                             (2, 'Bob', 92.0), 
                             (3, 'Charlie', 78.0)],
                            dtype=[('id', 'i4'), ('name', 'U10'), ('score', 'f4')])
print("Structured Array:\n", structured_array)

# Accessing fields in structured arrays
ids = structured_array['id']
names = structured_array['name']
scores = structured_array['score']
print("IDs:", ids)
print("Names:", names)
print("Scores:", scores)

# Using structured arrays for filtering
high_scorers = structured_array[structured_array['score'] > 80]
print("High Scorers (score > 80):\n", high_scorers)


=== Boolean Operations ===
Filtered Array (elements > 3): [4 5 6]
Logical AND (2 < elements < 5): [False False  True  True False False]
Logical OR (elements < 2 or > 5): [ True False False False False  True]

=== Vectorization ===
Vectorized Result (array * 2 + 5): [ 7  9 11 13 15 17]
Sum of 1 to 1,000,000 (Vectorized): 500000500000

=== Broadcasting and Strides ===
Broadcasted Addition:
 [[11 12 13]
 [14 15 16]]
Broadcasting with Vector:
 [[11 22 33]
 [14 25 36]]
Strided View (Every 2nd Column):
 [[1 3]
 [4 6]]

=== Structured Arrays ===
Structured Array:
 [(1, 'Alice', 85.5) (2, 'Bob', 92. ) (3, 'Charlie', 78. )]
IDs: [1 2 3]
Names: ['Alice' 'Bob' 'Charlie']
Scores: [85.5 92.  78. ]
High Scorers (score > 80):
 [(1, 'Alice', 85.5) (2, 'Bob', 92. )]
