In [2]:
import numpy as np

var1 = np.array([1,2,3])
var2 = np.array([4,5,6,7])

#Here we can't do the sum operation

######  If the arrays do not have the same rank (number of dimensions), prepend dimensions of size 1 to the smaller array until the ranks match.
###### Compare dimensions from right to left:
###### If dimensions are equal or one of them is 1, they are compatible.
###### Otherwise, they are incompatible, and broadcasting fails.

In [3]:
# Define a 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define a 1D array
b = np.array([10, 20, 30])

# Broadcasting adds 'b' to each row of 'a'
result = a + b

print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nResult of a + b:")
print(result)


Array a:
[[1 2 3]
 [4 5 6]]

Array b:
[10 20 30]

Result of a + b:
[[11 22 33]
 [14 25 36]]
