## Flatten : array.flatten(order='C')

#### Returns a new 1D array (copy) from any shape.

### 'C': Row-major order (default).
### 'F': Column-major order.
### 'A': Fortran order if original array is Fortran-contiguous, otherwise row-major.

In [10]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
flat1 = arr.flatten(order='C')
print()
flat2 = arr.flatten(order='F')
print()
flat3 = arr.flatten(order='A')
print()
flat4 = arr.flatten(order='K')

print(flat1)
print(flat2) 
print(flat3)  
print(flat4)   





[1 2 3 4]
[1 3 2 4]
[1 2 3 4]
[1 2 3 4]


### Ravel : numpy.ravel(arr, order='C')

### Returns a 1D array. Unlike flatten, it returns a view of the array whenever possible (no data copy).

### Modifying ravel output can affect the original array (if a view is returned).

In [11]:
arr = np.array([[1, 2], [3, 4]])
ravelled = arr.ravel()
print(ravelled)  # [1 2 3 4]


[1 2 3 4]


In [12]:
ravelled[0] = 100
print(arr)  # [[100   2]
            #  [  3   4]]

[[100   2]
 [  3   4]]
