#### numpy.insert()
#### The numpy.insert() function inserts values into an array along a specified axis. It creates a new array and does not modify the original array.

numpy.insert(arr, obj, values, axis=None)


#### arr: The input array.
#### obj: The index or indices before which values are to be inserted.
#### values: The values to insert into the array.
#### axis: The axis along which to insert. If None, the array is flattened first.


### Returns a new array with inserted value

In [1]:
import numpy as np

arr = np.array([10, 20, 30])
new_arr = np.insert(arr, 1, 15)
print(new_arr)  # [10 15 20 30]


[10 15 20 30]


## Insert into a 2D array (along a specific axis Along rows (axis=0):)

In [2]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 1, [5, 6], axis=0)
print(new_arr)
# [[1 2]
#  [5 6]
#  [3 4]]


[[1 2]
 [5 6]
 [3 4]]


In [3]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 1, [5, 6], axis=1)
print(new_arr)
# [[1 5 2]
#  [3 6 4]]


[[1 5 2]
 [3 6 4]]


 Insert without specifying an axis (axis=None)
The array is flattened first.

In [4]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 2, 5)
print(new_arr)  # [1 2 5 3 4]


[1 2 5 3 4]


#### numpy.delete()
#### The numpy.delete() function removes elements from an array along a specified axis. It creates a new array and does not modify the original array.

In [5]:
arr = np.array([10, 20, 30, 40])
new_arr = np.delete(arr, 2)
print(new_arr)  # [10 20 40]


[10 20 40]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
new_arr = np.delete(arr, 1, axis=0)
print(new_arr)
# [[1 2]
#  [5 6]]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = np.delete(arr, 1, axis=1)
print(new_arr)
# [[1 3]
#  [4 6]]


[[1 3]
 [4 6]]


##  Delete without specifying an axis (axis=None) The array is flattened first.

In [7]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.delete(arr, [0, 2])
print(new_arr)  # [2 4]


[2 4]


## Append Used to insert