### Join Array

### np.concatenate : Joins arrays along an existing axis.

#### syntax : np.concatenate((array1, array2, ...), axis=0)

In [3]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
var1 = np.array([2,3,4,5,6])

ar = np.concatenate((array, var1))
print(ar)

[1 2 3 4 5 2 3 4 5 6]


In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

ar3 = np.concatenate((arr1,arr2),axis=1)
print(ar3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### np.stack : Joins arrays along a new axis.

#### np.stack((array1, array2, ...), axis=0)


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.stack((arr1, arr2), axis=0)  # axis = 0 means vertical stacking
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


 #### np.hstack : Stacks arrays horizontally (along columns).

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)  # Output: [1 2 3 4 5 6]

ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])

result = np.hstack((ar1, ar2))
print(result)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]


[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


#### np.vstack : Stacks arrays vertically (along rows).

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)
# Output:
# [[1 2 3]
#  [4 5 6]]

ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])

result = np.vstack((ar1, ar2))
print(result)



[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### np.dstack : Stacks arrays along the third dimension.(height)

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.dstack((arr1, arr2))
print(result)
# Output:
# [[[1 4]
#   [2 5]
#   [3 6]]]

ar1 = np.array([[1, 2], [3, 4]])
ar2 = np.array([[5, 6], [7, 8]])

result = np.dstack((ar1, ar2))
print(result)
# Output:
# [[[1 5]
#   [2 6]
#   [3 7]
#   [4 8]]]

[[[1 4]
  [2 5]
  [3 6]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## Spliting array

In [29]:
var = np.array([1,2,3,4])
print(var)
ar = np.array_split(var,7) # if we want to split the array into parts more than size it will give some empty array
print(ar)

var1 = np.array([[1,2,3],[4,5,6]])
print(var1)
ar1 = np.array_split(var1,2) #Type of spliited array is list
print(ar1,type(ar1))

[1 2 3 4]
[array([1]), array([2]), array([3]), array([4]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]
[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])] <class 'list'>


#### np.hsplit : Splits an array horizontally (along columns).

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

result = np.hsplit(arr, 3)
print(result)
# Output:
# [array([[1],
#        [4]]), array([[2],
#        [5]]), array([[3],
#        [6]])]


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


#### np.vsplit:Splits an array vertically (along rows).

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

result = np.vsplit(arr, 2)
print(result)
# Output:
# [array([[1, 2, 3]]), array([[4, 5, 6]])]


[array([[1, 2, 3]]), array([[4, 5, 6]])]


#### np.dsplit : Splits an array along the third dimension.

In [32]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

result = np.dsplit(arr, 2)
print(result)
# Output:
# [array([[[1],
#         [3]],
#
#        [[5],
#         [7]]]), array([[[2],
#         [4]],
#
#        [[6],
#         [8]]])]


[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]
