In [2]:
import numpy as np

#### We use Where() function for searching a element

In [3]:
arr = np.array([1, 2, 3, 4, 5,2,3,4,5,6,6])
x = np.where(arr == 1) 
y = np.where(arr == 2) # we can give conditions like where((var%2)==0)
print(x)
print(y)

(array([0]),)
(array([1, 5]),)


### . Sorting in NumPy : Sorting functions to arrange data in ascending order.

np.sort(arr) : Returns a sorted copy of the array. The original array remains unchanged.

In [4]:
arr = np.array([30, 10, 20])
sorted_arr = np.sort(arr)
print(sorted_arr)  # [10 20 30]


[10 20 30]


In [16]:
arr1 = np.array([[1,3,2],[4,6,5]])
sorted_arr1 = np.sort(arr1,axis = 1) 
print(sorted_arr1)

[[1 2 3]
 [4 5 6]]


numpy.argsort() : Returns the indices that would sort the array.

In [12]:
arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)
print(sorted_indices)  # [1 2 0]


[1 2 0]


In [4]:
var2 = np.array(["a","c","b","k" ,"d","f"])
sorted = np.sort(var2)
print(sorted)


['a' 'b' 'c' 'd' 'f' 'k']


##### Searching in a Sorted Array (searchsorted)
##### a. numpy.searchsorted(sorted_arr, value, side='left')
##### Finds indices where elements should be inserted to maintain order.
##### side='left': Returns the first position.
##### side='right': Returns the last position.

In [3]:
sorted_arr = np.array([10, 20, 30, 40])
index = np.searchsorted(sorted_arr, 25)
print(index)  # 2


2


In [ ]:
import numpy as np

# Example 2D array (row-wise sorted)
arr = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [27, 29, 37, 48],
    [32, 33, 39, 50]
])

value = 29

# Find the position of 'value' in each row
positions = np.array([np.searchsorted(row, value, side='left') for row in arr])
print("Positions (left):", positions)

# Find the positions with 'right' option
positions_right = np.array([np.searchsorted(row, value, side='right') for row in arr])
print("Positions (right):", positions_right)


## Filtering

In [ ]:
varn = np.array([10, 20, 30, 40])
l = [False,True,False,True] #It gives only the value which is true
filter = varn[l]
print(filter)


[20 40]


#### numpy.isin(element, test_elements) : Checks if elements in the array belong to a set of values

In [ ]:
arr = np.array([10, 20, 30, 40])
mask = np.isin(arr, [10, 30])
print(mask)  # [ True False  True False]

[ True False  True False]
