## Shuffle : numpy.random.shuffle(arr)

##### Randomly shuffles the elements of an array in place along the first axis.
##### Does not return a new array; modifies the original array.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)  # Example: [3, 1, 5, 2, 4]


[4 1 2 3 5]


#### For multidimensional arrays, only the first axis is shuffled.

In [2]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
np.random.shuffle(arr)
print(arr)  # Rows are shuffled, e.g., [[5, 6], [1, 2], [3, 4]]


[[3 4]
 [5 6]
 [1 2]]


### Unique : numpy.unique(arr, return_counts=False, return_index=False, return_inverse=False)

#### Finds the unique elements in an array and optionally returns:
#### return_counts: Count of each unique element.
#### return_index: Indices of the first occurrences.
#### return_inverse: Indices to reconstruct the original array.

In [5]:
new_arr = np.array([1,2,2,3,4,5,5,4,6,7,6])
unique = np.unique(new_arr,return_index=True,return_inverse=True,return_counts=True)
print(unique)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 3, 4, 5, 8, 9]), array([0, 1, 1, 2, 3, 4, 4, 3, 5, 6, 5]), array([1, 2, 1, 2, 2, 2, 1]))


###  Resize
### numpy.resize(arr, new_shape)
### Returns a new array with the specified shape.
### If the new size is larger, the array will repeat its elements.

In [6]:
arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (2, 4))
print(resized_arr)
# [[1 2 3 1]
#  [2 3 1 2]]


[[1 2 3 1]
 [2 3 1 2]]
