In [ ]:
# In NumPy, you can find the transpose of an array using the .T attribute or the np.transpose() function.

# What is Transpose?
# The transpose of an array involves flipping it over its diagonal. Rows become columns, and columns become rows.

In [1]:
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Transpose using .T
transposed_array = array.T

print("Original Array:")
print(array)
print("Transposed Array:")
print(transposed_array)


Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [2]:
transposed_array = np.transpose(array)

print("Transposed Array (using np.transpose):")
print(transposed_array)


Transposed Array (using np.transpose):
[[1 4]
 [2 5]
 [3 6]]
