## Indexing

In [6]:
import numpy as np

In [ ]:
var = np.array([1, 2, 3, 4, 5])
#Positive         0, 1, 2, 3, 4 
#Negative        -5,-4,-3,-2,-1          
print(var[2]) # var[-3]

3


## Indexing of Multi-dimensional array

In [4]:
# Create a 2D array
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# Access specific elements
print(arr[0, 0])  # 1 (element in the 1st row, 1st column)
print(arr[1, 2])  # 6 (element in the 2nd row, 3rd column)


1
6


In [6]:
#Create a 3d array
arr = np.array([[[1,2,3,4],
                [5,6,7,8]],
                [[9,10,11,12],
                [13,14,15,16]]])
print(arr[0,0,2])

3


Integer Array Indexing

In [ ]:
arr = np.array([10, 20, 30, 40])
indices = [0, 2]
print(arr[indices])  # Output: [10, 30]

[10 30]


### Boolean Indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
mask = arr > 3 
print(arr[mask])  # Output: [4, 5] # indexing based on conditions


[4 5]


### Mixed Indexing: Combine integer arrays, slices, or boolean arrays.

In [4]:
arr = np.array([[10, 20], [30, 40], [50, 60]])
print(arr[[0, 1], [1, 0]])  # Output: [20, 30]


[20 30]


## Ellipsis (...) Indexing : The ellipsis (...) can be used to represent all dimensions not explicitly specified.

In [5]:
arr = np.random.rand(3, 4, 5)  # 3D array
print(arr[1, ..., 2])  # Access the 2nd slice in dimension 1 and 3rd column


[0.3110165  0.54478935 0.00833152 0.01413092]


## Fancy Indexing : Fancy indexing allows the use of multiple arrays of indices.

In [7]:
arr = np.array([10, 20, 30, 40, 50])
row_indices = np.array([0, 1, 3])
print(arr[row_indices])  # Output: [10, 20, 40]

[10 20 40]


In [8]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

row_indices = [0, 1, 2]  # Select rows
col_indices = [2, 1, 0]  # Select columns

result = arr[row_indices, col_indices]  # Matches (0,2), (1,1), (2,0)
print(result)  # Output: [30, 50, 70]


[30 50 70]
