## Basic Slicing

##### array[start:end:step]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    # Output: [20 30 40]
print(arr[:3])     # Output: [10 20 30]
print(arr[::2])    # Output: [10 30 50]
print(arr[::-1])   # Output: [50 40 30 20 10] (reverse order)


[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


##### array[row_start:row_end, col_start:col_end]


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[0:2, 1:3])  # Output: [[2 3]
                         #          [5 6]]

print(arr_2d[:, 1])      # Output: [2 5 8] (all rows, second column)

print(arr_2d[1, :])      # Output: [4 5 6] (second row, all columns)

print(arr_2d[::2, ::2])  # Output: [[1 3]
                         #          [7 9]] (skipping rows/columns)


##  Slicing in Higher Dimensions

In [4]:
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]],
                   [[9, 10], [11, 12]]])

print(arr_3d[0, :, :])  # Output: [[1 2]
                        #          [3 4]] (first "layer")
print(arr_3d[:, 1, 1])  # Output: [4 8 12] (specific element across layers)


[[1 2]
 [3 4]]
[ 4  8 12]


#### Slicing doesn't create a copy of the data; it creates a view. Modifying the slice will also modify the original array.

#### Boolean Indexing

In [4]:
arr = np.array([10, 15, 20, 25, 30])
mask = arr > 15
print(arr[mask])       # [20 25 30] (elements > 15)

arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d[arr_2d > 2])  # [3 4] (flattened view of elements > 2)


[20 25 30]
[3 4]
