## Arithmetic Operation in 1-d Array

In [28]:
import numpy as np

# Your data
data = np.array([3, 7, 2, 9, 12, 5])  # Replace with your array

# Calculations
min_val = data.min()
max_val = data.max()
sum_val = data.sum()
mean_val = data.mean()
median_val = np.median(data)
std_val = data.std()
var_val = data.var()

print(f"Min: {min_val}, Max: {max_val}, Sum: {sum_val}, Mean: {mean_val}, Median: {median_val}, Std: {std_val}, Var: {var_val}")


Min: 2, Max: 12, Sum: 38, Mean: 6.333333333333333, Median: 6.0, Std: 3.4480268109295333, Var: 11.888888888888888


## Addition

In [11]:
import numpy as np
var = np.array([1,2,3])
# varadd = var + 2
varadd = np.add(var,2)
print(varadd)

[3 4 5]


In [ ]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])
#varadd = var1 + var2
varadd = np.add(var1, var2)
print(varadd)

[5 7 9]


## Subtraction

In [4]:
var = np.array([1,2,3])
varadd = var - 2
print(varadd)

[-1  0  1]


In [5]:
var1 = np.array([1,2,3])
var2 = np.array([4,5,6])
varadd = var2 - var1
print(varadd)

[3 3 3]


#### Similarly we can perform other operation with numpy inbuilt functions

In [ ]:
### a+b : np.add(a,b)
### a-b : np.subtract(a,b)
### a*b : np.multiply(a,b)
### a/b : np.divide(a,b)
### a%b : np.mod(a,b)
### a**b : np.power(a,b)
### 1/a : np.reciprocal(a)

## Arithmetic operation in 2-d Array

In [14]:
var21 = np.array([[1,2,3],[4,5,6]])
var22 = np.array([[7,8,9],[10,11,12]])
print(var21)
print()
print(var22)
print()
varadd = np.add(var21, var22)
print(varadd)


[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 8 10 12]
 [14 16 18]]


In [23]:
var31 = np.array([1,2,3,4,5,6])
print(f"min: {np.min(var31)}")
print(f"max:{np.max(var31)}")
print(f"min: {np.argmin(var31)}") #Return index of min
print(f"max:{np.argmax(var31)}") #Return index of max
print(f"sqrt : {np.sqrt(var31)}")

min: 1
max:6
min: 0
max:5
sqrt : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


## 2-d array axis

In [ ]:
var1 = np.array([[1,2,3],[4,5,6]]) ## index for 2-d array , axis = 0 for column and axis = 1 for row
print(np.argmin(var1,axis = 1)) ## for axis = 1 it give 2 row's min
print(np.argmax(var1,axis = 0)) 


[0 0]
[1 1 1]


In [ ]:
#np.cos(x)
#np.sin(x)
#np.tan(x)
#np.cosh(x)
#np.sinh(x)
#np.tanh(x)

## CUMSUM

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4])
result = np.cumsum(arr)
print(result)  # Output: [ 1  3  6 10 ]


[ 1  3  6 10]


#### 2-d Array

In [30]:
arr = np.array([[1, 2], [3, 4]])
print(np.cumsum(arr))          # Flattened array: [ 1  3  6 10 ]
print(np.cumsum(arr, axis=0))  # Column-wise: [[1 3]
                               #               [3 7]]
print(np.cumsum(arr, axis=1))  # Row-wise: [[1  3]
                               #            [3  7]]


[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


## CUMPRODUCT

#### syntax : numpy.cumprod(array, axis=None, dtype=None)


In [31]:
arr = np.array([1, 2, 3, 4])
result = np.cumprod(arr)
print(result)  # Output: [ 1  2  6 24 ]


[ 1  2  6 24]


#### 2-d Array

In [32]:
arr = np.array([[1, 2], [3, 4]])
print(np.cumprod(arr))          # Flattened array: [ 1  2  6 24 ]
print(np.cumprod(arr, axis=0))  # Column-wise: [[1 3]
                                #               [2 8]]
print(np.cumprod(arr, axis=1))  # Row-wise: [[1  2]
                                #            [3 12]]


[ 1  2  6 24]
[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]
