# Random

## Rand() Function generates number between 0 and 1

In [5]:
import numpy as np 
var = np.random.rand(3)
print(var)

[0.10548115 0.29459725 0.0887541 ]


#### Multi-Dimensional array with rand() function

In [6]:
var1 = np.random.rand(2,3) 
print(var1)

[[0.52366413 0.55588084 0.64484194]
 [0.24225211 0.48682228 0.53629703]]


## randn() function prints value close to 0 may be positive or may be negative

In [7]:
var2 = np.random.randn(3)
print(var2)

[-0.96093878 -1.74981728  0.49682733]


## ranf() It returns specified shape of array and interval [0.0 , 1.0) 

In [8]:
var3 = np.random.ranf(5)
print(var3)

[0.71404712 0.31818471 0.4901981  0.97121189 0.89326074]


## randint() used to print a value between range of number 

In [9]:
var4 = np.random.randint(1,10,3) #(min,max,total_values) default gives 1 value
print(var4)

[7 6 8]


##  Random Sampling

### Choice : Randomly select elements from an array:

In [10]:
# Randomly pick 5 elements from the given array
sampled_array = np.random.choice([10, 20, 30, 40, 50], size=5)
print(sampled_array)


[30 20 50 10 50]


### Shuffle : Shuffle an array in place

In [11]:
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array)  # The order is randomized


[3 5 4 2 1]
