## NumPY Basics

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5]) ##Creating an array
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

### The Difference between array and list in python

#### Feature  :	NumPy Array :	Python List
#### Speed	   : Fast	       : Slower
#### Memory	:   Efficient	: Requires more memory
#### Data Types	: Homogeneous	: Heterogeneous
#### Mathematical Operations :	Element-wise supported :	Requires looping
#### Size Flexibility :	Fixed (immutable) :	Dynamic (mutable)
#### Use Case :	Numerical computing, data science :	General-purpose lists

In [5]:
x = [1,2,3,4,5]

y = np.array(x)

y

array([1, 2, 3, 4, 5])

#### Taking input for array as list items then convert it to array

In [6]:
l = []
for i in range(1,5):
    int_1 = int(input("Enter a number: "))
    l.append(int_1)

print(np.array(l))

[5 4 3 2]


### Types of Array
#### 1-D Array -> [1,2,3,4]
#### 2-D Array -> [[1,2,3,4]]
#### 3-D Array -> [[[1,2,3,4]]]
#### High Dimensional Array

In [7]:
print(np.array(l).ndim) #using ndim we can find the dimension of the array Syntax : arr.ndim

1


In [8]:
ar2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(ar2)
print(ar2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [9]:
arn = np.array([1,2,3,4],ndmin = 4) #ndmin is used to make n-dimension array
print(arn)
print(arn.ndim)

[[[[1 2 3 4]]]]
4


# Special NumPy Array

## Array filled with 0's

In [10]:
ar_zeros = np.zeros(4)
print(ar_zeros)
ar_zeros = np.zeros((3,4))
print(ar_zeros)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array filled with 1's

In [11]:
ar_one = np.ones(4)
print(ar_one)
ar_one = np.ones((3,4))
print(ar_one)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Empty Array

In [12]:
ar_empty = np.empty(4)
print(ar_empty)
ar_empty = np.empty((3,4))
print(ar_empty)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range 

In [13]:
ar_range = np.arange(4,8) #It always create 1-d array
print(ar_range)

[4 5 6 7]


## Array with Diagonal elements with 1

In [14]:
ar_diag = np.eye(3) #3*3 matrix(2-d matrix)
print(ar_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Linspace

In [15]:
ar_lin = np.linspace(2,10,num =5) #It always create 1-d array
print(ar_lin)

[ 2.  4.  6.  8. 10.]


## Array Attributes

In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", array.shape)       # (2, 3)
print("Size:", array.size)         # 6
print("Number of dimensions:", array.ndim)  # 2
print("Data type:", array.dtype)   # int32 (or platform-dependent)
print("Item size:", array.itemsize)  # Size of each element in bytes


Shape: (2, 3)
Size: 6
Number of dimensions: 2
Data type: int64
Item size: 8
