## Shape

In [2]:
import numpy as np

In [6]:
var = np.array([[1,2],[3,4]])
print(var)
print()
print(var.shape)

[[1 2]
 [3 4]]

(2, 2)


In [8]:
var2 = np.array([1,2,3,4],ndmin=4)
print(var2)
print()
print(var2.shape)

[[[[1 2 3 4]]]]

(1, 1, 1, 4)


## Reshape

In [10]:
var3 = np.array([1,2,3,4,5,6])
print(var3)
x = var3.reshape(3,2)
print(x)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
var4 = np.array([1,2,3,4,5,6])
print(var4)
print(var4.ndim)
print()
x = var4.reshape(3,2)
print(x)
print(x.ndim)
print()
new = x.reshape(-1)
print(new)
print(new.ndim)


[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2

[1 2 3 4 5 6]
1
