In [1]:
import numpy as np

## Iterating a 1-D Array

In [7]:
new = np.array([1,2,3,4])

In [8]:
for a in new:
    print(a)

1
2
3
4


## Iterating a 2-D Array

In [10]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
for a in x:
        print(a)

[1 2 3]
[4 5 6]
[7 8 9]


In [12]:
## All elements of the array
for a in x:
    for b in a:
        print(b)

1
2
3
4
5
6
7
8
9


## Iterating a 3-D Array

In [13]:
x1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x1.ndim)

3


In [15]:
for a in x1:
    for b in a:
        for c in b:
            print(c)
print()
for a in x1:
    print(a)

1
2
3
4
5
6
7
8
9

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Iterating through nditer

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
for element in np.nditer(arr):  #we can use this nditer and print all elements without so much loops
    print(element)

1
2
3
4
5
6
7
8
9


## Iterating with Indexes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")


Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


In [19]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use nditer with readwrite mode
for element in np.nditer(arr, op_flags=['readwrite']):
    element[...] *= 2  # Multiply each element by 2

print(arr)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
